name: web-docker

on:
  push:
    branches: [ main, dev ]
    tags:
    - 'v*'
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:
  build-web:
    name: Build web docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build web
        run: make build-docker

      - name: Get tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Push to Github packages
        env:
          GITHUB_IMAGE_NAME: docker.pkg.github.com/${{ github.repository }}/nocalhost-web
        run: |
          echo ${{ secrets.GPR_PASS }} | docker login docker.pkg.github.com -u ${{ secrets.GPR_USER }} --password-stdin
          docker tag nocalhost-web:${GITHUB_SHA} ${GITHUB_IMAGE_NAME}:${GITHUB_SHA}
          docker push ${GITHUB_IMAGE_NAME}:${GITHUB_SHA}

      - name: Push main to Github packages
        if: ${{ github.ref == 'refs/heads/main'}}
        env:
          GITHUB_IMAGE_NAME: docker.pkg.github.com/${{ github.repository }}/nocalhost-web
        run: |
          echo ${{ secrets.GPR_PASS }} | docker login docker.pkg.github.com -u ${{ secrets.GPR_USER }} --password-stdin
          docker tag nocalhost-web:${GITHUB_SHA} ${GITHUB_IMAGE_NAME}:main
          docker push ${GITHUB_IMAGE_NAME}:main

      - name: Push dev to Github packages
        if: ${{ github.ref == 'refs/heads/dev'}}
        env:
          GITHUB_IMAGE_NAME: docker.pkg.github.com/${{ github.repository }}/nocalhost-web
        run: |
          echo ${{ secrets.GPR_PASS }} | docker login docker.pkg.github.com -u ${{ secrets.GPR_USER }} --password-stdin
          docker tag nocalhost-web:${GITHUB_SHA} ${GITHUB_IMAGE_NAME}:dev
          docker push ${GITHUB_IMAGE_NAME}:dev

      - name: Push release to Github packages
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          GITHUB_IMAGE_NAME: docker.pkg.github.com/${{ github.repository }}/nocalhost-web
        run: |
          echo ${{ secrets.GPR_PASS }} | docker login docker.pkg.github.com -u ${{ secrets.GPR_USER }} --password-stdin
          docker tag nocalhost-web:${GITHUB_SHA} ${GITHUB_IMAGE_NAME}:${{ env.RELEASE_VERSION }}
          docker tag nocalhost-web:${GITHUB_SHA} ${GITHUB_IMAGE_NAME}:latest
          docker push ${GITHUB_IMAGE_NAME}:${{ env.RELEASE_VERSION }}
          docker push ${GITHUB_IMAGE_NAME}:latest

      - name: Push to Coding Artifacts
        if: ${{ github.repository == 'nocalhost/nocalhost-web' }}
        env:
          CODING_IMAGE_NAME: codingcorp-docker.pkg.coding.net/nocalhost/public/nocalhost-web
        run: |
          echo ${{ secrets.CODING_ARTIFACTS_PASS }} | docker login codingcorp-docker.pkg.coding.net -u ${{ secrets.CODING_ARTIFACTS_USER }} --password-stdin
          docker tag nocalhost-web:${GITHUB_SHA} ${CODING_IMAGE_NAME}:${GITHUB_SHA}
          docker push ${CODING_IMAGE_NAME}:${GITHUB_SHA}

      - name: Push main to Coding Artifacts
        if: ${{ github.ref == 'refs/heads/main' && github.repository == 'nocalhost/nocalhost-web' }}
        env:
          CODING_IMAGE_NAME: codingcorp-docker.pkg.coding.net/nocalhost/public/nocalhost-web
        run: |
          echo ${{ secrets.CODING_ARTIFACTS_PASS }} | docker login codingcorp-docker.pkg.coding.net -u ${{ secrets.CODING_ARTIFACTS_USER }} --password-stdin
          docker tag nocalhost-web:${GITHUB_SHA} ${CODING_IMAGE_NAME}:main
          docker push ${CODING_IMAGE_NAME}:main

      - name: Push dev to Coding Artifacts
        if: ${{ github.ref == 'refs/heads/dev' && github.repository == 'nocalhost/nocalhost-web' }}
        env:
          CODING_IMAGE_NAME: codingcorp-docker.pkg.coding.net/nocalhost/public/nocalhost-web
        run: |
          echo ${{ secrets.CODING_ARTIFACTS_PASS }} | docker login codingcorp-docker.pkg.coding.net -u ${{ secrets.CODING_ARTIFACTS_USER }} --password-stdin
          docker tag nocalhost-web:${GITHUB_SHA} ${CODING_IMAGE_NAME}:dev
          docker push ${CODING_IMAGE_NAME}:dev

      - name: Push release to Coding Artifacts
        if:  ${{ startsWith(github.ref, 'refs/tags/v') &&  github.repository == 'nocalhost/nocalhost-web' }}
        env:
          CODING_IMAGE_NAME: codingcorp-docker.pkg.coding.net/nocalhost/public/nocalhost-web
        run: |
          echo ${{ secrets.CODING_ARTIFACTS_PASS }} | docker login codingcorp-docker.pkg.coding.net -u ${{ secrets.CODING_ARTIFACTS_USER }} --password-stdin
          docker tag nocalhost-web:${GITHUB_SHA} ${CODING_IMAGE_NAME}:${{ env.RELEASE_VERSION }}
          docker tag nocalhost-web:${GITHUB_SHA} ${CODING_IMAGE_NAME}:latest
          docker push ${CODING_IMAGE_NAME}:${{ env.RELEASE_VERSION }}
          docker push ${CODING_IMAGE_NAME}:latest
